<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>To Do List</h1>
        <nav>
            <ul>
                <li>Enlace 1</li>
                <li><a href="logout">Cerrar sesion</a></li>
            </ul>
        </nav>
    </header>
    <main>