<form action="toregister" method="POST">
    <label>Registrarse</label>
    <label>Nombre:</label>
    <input type="text" name="name" placeholder="Nombre"/>
    <label>Email:</label>
    <input type="text" name="email" placeholder="Email"/>
    <label>Contraseña:</label>
    <input type="password" name="password" placeholder="Contraseña"/>
    <button type="submit">Registrarse</button>
</form>
<p>Ya tienes una cuenta? <a href="login">Login</a></p>
<?= $message ?>