<article class="box-tasks">
    <?php foreach($tasks as $task) : ?>
        <div class="tasks">
            <h2><?=$task->title?></h2>
            <p><?=$task->description?></p>
            <p><?=$task->finalize?></p>
            <input type="button" value="Editar">
            <a href="home/delete/<?=$task->id_task?>">Eliminar</a>
            <a href="home/finalize/<?=$task->id_task?>">Finalizar</a>
        </div>
    <?php endforeach;?>
</article>